### PR TITLE
initialzed inertia properly

### PR DESCRIPTION
**Pull request by Rajce23**
Initialzed inertia properly and updated packages to enable inertia initialization

### CODE REVIEW

**Review by SedlarDavid — APPROVED** [review]
Seems ok, GJ

**Review by SedlarDavid — CHANGES_REQUESTED** [review]
Change designated branch, you dont want main, you want develop right?

**Comment by Rajce23** [comment]
We have develop🧐

**Comment by Rajce23** [comment]
If we have develop the not to the main😄

**Comment by Rajce23** [comment]
It is changer to develop

**Review by SedlarDavid — APPROVED** [review]
Feel free to Squash and merge, delete inertia-init branch, and please cleanup your other branches aswell :D

**Pull request merged**
